name: Build binary executable

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build executable
      run: |
        pyinstaller --onefile main.py -n domainfinder
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-binary-${{ matrix.os }}
        path: dist/main
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
